esphome:
  name: remote
  friendly_name: RemoteControl

esp32:
  board: nodemcu-32s
  framework:
    type: esp-idf

external_components:
  - source:
      type: local
      path: components
    components: [ somfy_cover ]

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "<ADD AN ENCRYPTION KEY HER>" 

ota:
  - platform: esphome
    password: "<SET A PASSWORD HERE>"
  #- platform: web_server

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

spi:
  clk_pin: GPIO18
  mosi_pin: GPIO23
  miso_pin: GPIO19

cc1101:
  frequency: 433.42MHz
  cs_pin: GPIO5
button:
  - platform: template
    id: "program_awning"
    name: "PROG button"

remote_transmitter:
  id: "transmitter"
  pin: GPIO2
  carrier_duty_percent: 100%
  on_transmit:
    then:
      - cc1101.begin_tx
  on_complete:
    then:
      - cc1101.set_idle
cover:
  - platform: somfy_cover
    id: awning
    name: "Awning"
    device_class: awning
    open_duration: 55s
    close_duration: 55s
    storage_key: storekey
    remote_code: 0xabcdef
    prog_button: program_awning
    remote_transmitter: transmitter

